/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo.core;

public class Utils {
     public boolean isAllPositiveNumbers(String ...strArray) {
    	boolean result=false;
    	demo.StringUtils stringUtils=new demo.StringUtils();
    	if(strArray==null) {
    		return result;
    	}
    	
    	for(String stringElement:strArray) {
    		if(stringElement==null) {
    			return false;
    		}
    		if(stringUtils.isPositiveNumber(stringElement)) {
    			result=true;
    		}else {
    			return false;
    		}
    	}
    	return result;
    }
}
